main/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views 
from django.conf.urls import include
from django.views.generic.base import RedirectView
from main.decorators import *

urlpatterns = [
		
		path('', views.index, name='index'),
		path('student', views.student_dashboard, name='student_dashboard'),
		path('student/book/upload', views.student_book_upload, name='student_book_upload'),
		path('student/note/upload', views.student_note_upload, name='student_note_upload'),
		path('student/courses', views.student_courses, name='student_courses'),
		path('student/club/courses', views.student_club_courses, name='student_club_courses'),
		path('department', views.department_dashboard, name='department_dashboard'),
		path('admind', views.admin_dashboard, name='admin_dashboard'),
		path('club', views.club_dashboard, name='club_dashboard'),
		path('book/approval', views.book_approval, name='book_approval'),
		path('note/approval', views.note_approval, name='note_approval'),
		path('misc/approval', views.misc_approval, name='misc_approval'),
		path('add/dept', views.add_dept, name='add_dept'),
		path('add/course', views.add_course, name='add_course'),
		path('misc/upload', views.misc_upload, name='misc_upload'),
		path('video/upload', views.video_upload, name='video_upload'),
		path('api/courses',views.get_courses, name='api_courses'),
		path('login', views.events_login, name='events_login'),
		path('redirect', views.redirect_ac, name='redirect_ac'),
		path('logout/', views.logout_view, name='logout'),

]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid

from django.utils.translation import ugettext as translate
from django.utils.timezone import now
from main.file_format import ContentTypeRestrictedFileField
import datetime

class AutoCreatedUpdatedMixin(models.Model):

	created_at = models.DateTimeField(
		verbose_name=translate('created at'),
		unique=False,
		null=True,
		blank=True,
		db_index=True,
	)

	updated_at = models.DateTimeField(
		verbose_name=translate('updated at'),
		unique=False,
		null=True,
		blank=True,
		db_index=True,
	)

	class Meta:
		abstract = True

	def save(self, *args, **kwargs):
		if not self.created_at:
			self.created_at = now()
			self.updated_at = self.created_at
		else:
			auto_updated_at_is_disabled = kwargs.pop('disable_auto_updated_at', False)
			if not auto_updated_at_is_disabled:
				self.updated_at = now()
		super(AutoCreatedUpdatedMixin, self).save(*args, **kwargs)


class SoftDeleteMixin(models.Model):

	deleted_at = models.DateTimeField(
		verbose_name=translate('deleted at'),
		unique=False,
		null=True,
		blank=True,
		db_index=True,
	)

	class Meta:
		abstract = True

	def delete(self, using=None, keep_parents=False):
		self.deleted_at = now()
		kwargs = {
			'using': using,
		}
		if hasattr(self, 'updated_at'):
			kwargs['disable_auto_updated_at'] = True
		self.save(**kwargs)

class Department(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Course(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	name = models.CharField(max_length=100)
	department = models.ForeignKey(Department,on_delete=models.CASCADE)

	def __str__(self):
		return self.name + ", " + self.department.name

	def as_dict(self):
		return {
			"name":self.name,
			"id":self.id
		}


class User(AbstractUser,AutoCreatedUpdatedMixin,SoftDeleteMixin):
	is_student = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)
	is_department = models.BooleanField(default=False)
	is_club = models.BooleanField(default=False)
	department = models.ForeignKey(Department,on_delete=models.CASCADE , related_name='dept',blank=True, null=True)
	contact = models.CharField(max_length=20, default=False)
	roll = models.CharField(max_length=20, default=False)
	contri = models.IntegerField(default=0)
	

	# def save(self, *args, **kwargs):
	# 	super(User, self).save(*args, **kwargs)
	# 	self.t_id = "T19"+str(12000+int(self.id)) 
	# 	super(User, self).save(*args, **kwargs)

	def __str__(self):
		return self.username

class Book(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	user = models.ForeignKey(User,on_delete=models.CASCADE , related_name='book')
	document = ContentTypeRestrictedFileField(upload_to='static/books/', content_types=['application/docx', 'application/pdf', 'application/doc', 'application/odt', ],max_upload_size=5242880,blank=True, null=True)
	author = models.CharField(max_length=100, blank=False)
	title = models.CharField(max_length=100, blank=False)
	is_approved = models.IntegerField(default=0)

class Note(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	user = models.ForeignKey(User,on_delete=models.CASCADE , related_name='note')
	document = ContentTypeRestrictedFileField(upload_to='static/notes/', content_types=['application/docx', 'application/pdf', 'application/doc', 'application/odt', ],max_upload_size=5242880,blank=True, null=True)
	course = models.ForeignKey(Course,on_delete=models.CASCADE , related_name='nc')
	title = models.CharField(max_length=100, blank=False)
	is_approved = models.IntegerField(default=0)

class MiscNote(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	user = models.ForeignKey(User,on_delete=models.CASCADE , related_name='mis')
	document = ContentTypeRestrictedFileField(upload_to='static/misc/', content_types=['application/docx', 'application/pdf', 'application/doc', 'application/odt', ],max_upload_size=5242880,blank=True, null=True)
	desc = models.CharField(max_length=100, blank=False)
	title = models.CharField(max_length=100, blank=False)
	is_approved = models.IntegerField(default=0)

class CourseVideo(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE , related_name='video')
	course = models.ForeignKey(Course,on_delete=models.CASCADE , related_name='vc')
	title= models.CharField(max_length=500)
	document= models.FileField(upload_to='static/videos/', null=True, verbose_name="")

	def __str__(self):
		return self.title + ": " + str(self.document)

main/templates/general/misc_upload.html
{% extends 'layouts/master.html' %}
{%block title%}Misc | Upload{%endblock%}
{%load static%}

{%block head%}
<style type="text/css">
    .query{
        color:black;
    }
    .loader {
      border: 8px solid #f3f3f3;
      border-radius: 50%;
      border-top: 8px solid #00b7ff;
      width: 50px;
      height: 50px;
      margin:auto;
      -webkit-animation: spin 2s linear infinite; /* Safari */
      animation: spin 2s linear infinite;
  }

  /* Safari */
  @-webkit-keyframes spin {
      0% { -webkit-transform: rotate(0deg); }
      100% { -webkit-transform: rotate(360deg); }
  }

  @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
  }
</style>
{%endblock%}
{% block content %}


<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1 ><b> Upload Generic Books / Articles / Published Papers </b></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-4"></div>
                    <div class="col-xs-12 col-sm-12 col-md-4">
                          {% if msg == "Uploaded successfully" %}
                        <div class="alert alert-success" role="alert">
                          File sent for Approval
                        </div>
                        {% endif %}
                        {% if msg == "Error while uploading" %}
                        <div class="alert alert-danger" role="alert">
                          Error while uploading! Try again.
                        </div>
                        {% endif %}
                          <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                              <div class="form-group">
                                <div class="col col-md-3"><label for="id_document">File :</label></div>
                                <div class="col-12 col-md-9"><input type="file" name="document" class="form-control-file" id="id_document"><small class="help-block form-text">(PDF format)</small></div>
                              </div>
                        <div class="row form-group">
                            <div class="col col-md-3"><label for="id_desc" class=" form-control-label">Description:</label></div>
                            <div class="col-12 col-md-9"><textarea id="id_desc" name="desc" class="form-control" ></textarea></div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3"><label for="id_title" class=" form-control-label">Title :</label></div>
                            <div class="col-12 col-md-9"><input type="text" id="id_title" name="title" class="form-control" ></div>
                        </div>


                    <div class="row">
                    <div class="col-xs-3 col-sm-3"></div>
                    <div class="col-xs-6 col-sm-6 text-center">
                        <button type="submit" name="submit" class="btn btn-success">Upload</button>
                    </div>
                    <div class="col-xs-3 col-sm-3"></div>
                    </div>
                          </form>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4"></div>

                    <div class="col-md-6 col-xs-12">

                    </div>
                    <div class="col-md-6 col-xs-12">
                        
                    </div>
                    <div class="col-md-6 col-xs-12">
                        
                    </div>

                    <div class="col-md-6 col-xs-12">
                        
                    </div>


                </div>
            
    
    </div><!-- .animated -->
</div>


{% endblock %}

{%block script%}

<script type="text/javascript">
    $("#all_adding").addClass('active');
    $("#misc").children().addClass('_active');
</script>

{%endblock%}

main/templates/general/video_upload.html
{% extends 'layouts/master.html' %}
{%block title%}Course or Video | Upload{%endblock%}
{%load static%}

{%block head%}
<style type="text/css">
    .query{
        color:black;
    }
    .loader {
      border: 8px solid #f3f3f3;
      border-radius: 50%;
      border-top: 8px solid #00b7ff;
      width: 50px;
      height: 50px;
      margin:auto;
      -webkit-animation: spin 2s linear infinite; /* Safari */
      animation: spin 2s linear infinite;
  }

  /* Safari */
  @-webkit-keyframes spin {
      0% { -webkit-transform: rotate(0deg); }
      100% { -webkit-transform: rotate(360deg); }
  }

  @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
  }
</style>
{%endblock%}
{% block content %}


<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1 ><b> Upload Video </b></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-4"></div>
                    <div class="col-xs-12 col-sm-12 col-md-4">
                            {% if msg == "Video uploaded successfully" %}
                            <div class="alert alert-success" role="alert">
                              Video uploaded successfully
                            </div>
                            {% endif %}
                            {% if msg == "Error while uploading" %}
                            <div class="alert alert-danger" role="alert">
                              Error while uploading! Try again.
                            </div>
                            {% endif %}
                          <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                         <div class="form-group">
                                <div class="col col-md-3"><label for="id_document">Video:</label></div>
                                <div class="col-12 col-md-9"><input type="file" name="document" class="form-control-file" id="id_document"></div>
                              </div>
                        <div class="row form-group">
                          <div class="col col-md-3"><label for="id_department" class=" form-control-label">Select Department</label></div>
                          <div class="col-12 col-md-9">
                            <select name="department" id="id_department" class="form-control" required>
                              <option value="">Select Department</option>
                              {%for department in departments%}
                              <option value="{{department.id}}">{{department.name}}</option>
                              {%endfor%}      
                            </select>
                          </div>
                        </div>

                        <div class="row form-group">
                          <div class="col col-md-3"><label for="id_course" class=" form-control-label">Select Course</label></div>
                          <div class="col-12 col-md-9">
                            <select name="course" id="id_course" class="form-control" required>
                              <option value="0">Select Course</option>   
                            </select>
                          </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3"><label for="id_title" class=" form-control-label">Title :</label></div>
                            <div class="col-12 col-md-9"><input type="text" id="id_title" name="title" class="form-control" ></div>
                        </div>


                    <div class="row">
                    <div class="col-xs-3 col-sm-3"></div>
                    <div class="col-xs-6 col-sm-6 text-center">
                        <button type="submit" name="submit" class="btn btn-success">Upload</button>
                    </div>
                    <div class="col-xs-3 col-sm-3"></div>
                    </div>
                          </form>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4"></div>

                    <div class="col-md-6 col-xs-12">

                    </div>
                    <div class="col-md-6 col-xs-12">
                        
                    </div>
                    <div class="col-md-6 col-xs-12">
                        
                    </div>

                    <div class="col-md-6 col-xs-12">
                        
                    </div>
                </div>
    </div><!-- .animated -->
</div>


{% endblock %}

{%block script%}

<script type="text/javascript">
    $("#video_co").addClass('active');

$("#id_course").prop('disabled',true);

    $("#id_department").on('change',function(){
        text1 = $('#id_department').val();
        if(text1===""){
            $("#id_course").prop('disabled',true);
            $("#id_course").empty()
            $("#id_course").append('<option value="">Select course</option>');

        }
        else{
            $.ajax({
                type: "POST",
                url: "{%url 'api_courses'%}",
                data: {'department':text1,csrfmiddlewaretoken:'{{ csrf_token }}'},
                success: function(courses){
                    $("#id_course").prop('disabled',false);
                    $("#id_course").empty()
                    $("#id_course").append('<option value="">Select Course</option>');
                    for(course in courses){
                        $("#id_course").append('<option value="'+courses[course]['id']+'">'+courses[course]['name']+'</option>');
                    }
                }
            });
        }
    });
</script>
{%endblock%}